import random
import itertools
import re
from ollama import chat
import json
import time

degrees = [
    "BSc", "MSc", "PhD", "Diploma", "MBA", "BEng", "MEng", "BS", "MS", "DEng",
    "DPhil", "Associate's Degree", "Professional Certificate", "Bachelor of Science",
    "Master of Science", "Doctor of Philosophy", "Bachelor of Engineering",
    "Master of Engineering", "Bachelor of Technology", "Master of Technology",
    "Bachelor of Computer Science", "Master of Computer Science", "Bachelor of Arts",
    "Master of Arts", "Bachelor of Business Administration", "Master of Business Administration",
    "Doctor of Business Administration", "Associate of Science", "Associate of Applied Science",
    "Higher National Diploma", "Postgraduate Diploma", "Postgraduate Certificate",
    "Graduate Certificate", "Graduate Diploma", "Doctor of Engineering", "Doctor of Science",
    "Licentiate", "Candidatus", "Magister", "Staatsexamen", "MPhil", "Master of Research",
    "Integrated Master's Degree", "Professional Doctorate", "Executive MBA",
    "Global MBA", "Specialist Degree", "Bachelor of Applied Science", "Master of Applied Science",
    "Bachelor of Information Technology", "Master of Information Technology",
    "Doctor of Information Technology", "Bachelor of Software Engineering",
    "Master of Software Engineering", "Bachelor of Data Science", "Master of Data Science",
    "Bachelor of Cybersecurity", "Master of Cybersecurity", "Bachelor of Computer Applications",
    "Master of Computer Applications", "Bachelor of Science in Information Systems",
    "Master of Science in Information Systems", "Bachelor of Science in Business Administration",
    "Master of Public Administration", "Doctor of Public Administration", "Juris Doctor",
    "Master of Laws", "Doctor of Medicine", "Bachelor of Medicine, Bachelor of Surgery",
    "Bachelor of Design", "Master of Design", "Bachelor of Fine Arts", "Master of Fine Arts",
    "Bachelor of Architecture", "Master of Architecture", "Professional Engineer",
    "Chartered Engineer", "Bachelor of Commerce", "Master of Commerce", "Honours Degree",
    "Vocational Degree", "Technical Degree", "Foundation Degree", "Advanced Diploma",
    "Specialist Diploma", "Certificate of Higher Education", "Dual Degree",
    "Joint PhD", "Industrial PhD", "Professional Science Master's", "Bachelor of Mathematics",
    "Master of Mathematics", "Bachelor of Statistics", "Master of Statistics",
    "Bachelor of Physics", "Master of Physics", "Bachelor of Electrical Engineering",
    "Master of Electrical Engineering", "Bachelor of Mechanical Engineering",
    "Master of Mechanical Engineering", "Bachelor of Civil Engineering", "Master of Civil Engineering",
    "Bachelor of Chemical Engineering", "Master of Chemical Engineering", "Bachelor of Aerospace Engineering",
    "Master of Aerospace Engineering", "Bachelor of Biomedical Engineering", "Master of Biomedical Engineering",
    "Bachelor of Environmental Engineering", "Master of Environmental Engineering", "Bachelor of Industrial Engineering",
    "Master of Industrial Engineering", "Bachelor of Management Information Systems", "Master of Management Information Systems",
    "Bachelor of Game Design and Development", "Master of Game Design and Development", "Bachelor of Interactive Entertainment",
    "Master of Interactive Entertainment", "Bachelor of Network and Security", "Master of Network and Security",
    "Bachelor of Robotics and Mechatronics", "Master of Robotics and Mechatronics", "Bachelor of Cognitive Science",
    "Master of Cognitive Science", "Bachelor of Computational Linguistics", "Master of Computational Linguistics",
    "Bachelor of Bioinformatics", "Master of Bioinformatics", "Bachelor of Geomatics Engineering",
    "Master of Geomatics Engineering", "Bachelor of Systems Engineering", "Master of Systems Engineering",
    "Nano Degree", "MicroMasters", "Executive Education Certificate", "Certificate of Completion",
    "Professional Diploma", "Advanced Professional Certificate", "Graduate Apprenticeship",
    "Bachelor of Science in Engineering", "Master of Science in Engineering", "Doctor of Engineering Science",
    "Bachelor of Science in Computer Engineering", "Master of Science in Computer Engineering",
    "Bachelor of Science in Electrical and Computer Engineering", "Master of Science in Electrical and Computer Engineering",

    "Bachelor of Science in Artificial Intelligence", "Master of Science in Artificial Intelligence"
]

majors = [
    "Computer Science", "Artificial Intelligence", "Data Science", "Software Engineering",
    "Cybersecurity", "Information Systems", "Computer Engineering", "Information Technology",
    "Machine Learning", "Robotics", "Data Analytics", "Computational Linguistics",
    "Bioinformatics", "Network Engineering", "Cloud Computing", "Electrical Engineering",
    "Mathematics", "Statistics", "Physics", "Mechanical Engineering", "Systems Engineering",
    "Management Information Systems", "Human-Computer Interaction", "Computer Graphics",
    "Game Design and Development", "Information Security", "Network Administration",
    "Database Management", "Web Development", "Mobile Application Development",
    "Embedded Systems", "Theoretical Computer Science", "Algorithms and Complexity",
    "Computer Architecture", "Operating Systems", "Distributed Systems", "Parallel Computing",
    "High-Performance Computing", "Scientific Computing", "Quantum Computing",
    "Cognitive Science", "Computational Science", "Computational Biology",
    "Health Informatics", "Financial Engineering", "Business Analytics", "Operations Research",
    "Industrial Engineering", "Control Systems Engineering", "Mechatronics",
    "Aerospace Engineering", "Biomedical Engineering", "Chemical Engineering",
    "Civil Engineering", "Environmental Engineering", "Geomatics Engineering",
    "Materials Science and Engineering", "Software Development", "Computer Programming",
    "Applied Mathematics", "Pure Mathematics", "Actuarial Science", "Applied Physics",
    "Engineering Physics", "Computational Chemistry", "Digital Media", "Interactive Technology",
    "Computer Animation", "Visual Effects", "User Experience Design", "User Interface Design",
    "Product Design", "Information Architecture", "Knowledge Management", "Decision Science",
    "Intelligence Analysis", "Digital Forensics", "Ethical Hacking", "IT Audit and Control",
    "Cloud Architecture", "DevOps", "Site Reliability Engineering", "Automation Engineering",
    "Telecommunications Engineering", "Wireless Communication", "Optical Engineering",
    "Signal Processing", "Image Processing", "Natural Language Processing",
    "Computer Vision", "Machine Intelligence", "Autonomous Systems", "Data Warehousing",
    "Big Data Technologies", "Business Intelligence", "E-commerce Technology",
    "Enterprise Software Development", "Scientific Visualization", "Computer Science and Economics",
    "Computer Science and Linguistics", "Computer Science and Mathematics",
    "Computer Science and Physics", "Electrical and Computer Engineering", "Computer and Information Science",
    "Information Science", "Library and Information Science", "Computer Systems Engineering",
    "Network and Telecommunications Engineering", "Software Systems Engineering",
    "Web Design and Development", "Mobile and Web Computing", "Data Management and Analytics",
    "Artificial Intelligence and Machine Learning", "Robotics and Artificial Intelligence",
    "Computer Science with a specialization in Gaming", "Computer Science with a specialization in Security",
    "Information Technology Management", "Technology and Information Management", "Technical Communication",
    "Computer Forensics", "Network Security", "Secure Software Development",
    "Information Assurance", "Systems and Network Administration", "Cloud and Systems Administration",
    "Data Modeling/Warehousing and Database Administration", "Web and Mobile Computing",
    "Human-Centered Computing", "Social Computing", "Ubiquitous Computing",
    "Bio-inspired Computing", "Computational Finance", "Computational Mechanics",
    "Geoinformatics", "Mathematical and Computer Sciences", "Numerical Analysis",
    "Simulation, Modeling, and Analysis", "Software Practice", "Computer Engineering Technology",
    "Electrical Engineering Technology", "Mechanical Engineering Technology",
    "Industrial Technology", "Computer Information Systems", "Applied Computer Science"
]

universities = [
    "Cairo University", "Ain Shams University", "MIT", "Stanford University", "Alexandria University",
    "Helwan University", "German University in Cairo", "The American University in Cairo",
    "Carnegie Mellon University", "University of California, Berkeley", "Harvard University",
    "University of Cambridge", "University of Oxford", "Zewail City of Science and Technology",
    "Egypt-Japan University of Science and Technology (E-JUST)", "Nile University", "Mansoura University",
    "Assiut University", "Zagazig University", "Benha University", "Suez Canal University",
    "Tanta University", "Menoufia University", "Kafr El Sheikh University", "British University in Egypt",

    "Future University in Egypt", "Canadian International College", "Ahram Canadian University",
    "Misr University for Science and Technology", "October 6 University", "Arab Academy for Science, Technology & Maritime Transport",
    "California Institute of Technology (Caltech)", "Princeton University", "University of Chicago",
    "Columbia University", "Yale University", "University of Pennsylvania", "Johns Hopkins University",
    "Northwestern University", "Duke University", "Cornell University", "University of Michigan-Ann Arbor",
    "University of California, Los Angeles (UCLA)", "University of Southern California (USC)",
    "Georgia Institute of Technology", "University of Illinois Urbana-Champaign", "University of Texas at Austin",
    "University of Washington", "University of Wisconsin-Madison", "Purdue University", "Texas A&M University",
    "University of California, San Diego (UCSD)", "University of Maryland, College Park",
    "University of Minnesota, Twin Cities", "Ohio State University", "University of Florida",
    "University of North Carolina at Chapel Hill", "Virginia Tech", "Rice University",
    "University of Waterloo", "University of Toronto", "McGill University", "University of British Columbia",
    "University of Alberta", "McMaster University", "Queen's University", "University of Montreal",
    "Imperial College London", "University College London (UCL)", "University of Edinburgh",
    "King's College London", "University of Manchester", "University of Bristol", "University of Warwick",
    "ETH Zurich (Swiss Federal Institute of Technology)", "EPFL (École polytechnique fédérale de Lausanne)",
    "Technical University of Munich (TUM)", "RWTH Aachen University", "Delft University of Technology (TU Delft)",
    "KTH Royal Institute of Technology", "Politecnico di Milano", "Paris-Saclay University",
    "Sorbonne University", "PSL Research University", "National University of Singapore (NUS)",
    "Nanyang Technological University (NTU)", "Tsinghua University", "Peking University",

    "Shanghai Jiao Tong University", "University of Tokyo", "Kyoto University",
    "Seoul National University", "KAIST (Korea Advanced Institute of Science and Technology)",
    "Indian Institute of Technology Bombay (IIT Bombay)", "Indian Institute of Technology Delhi (IIT Delhi)",
    "Australian National University", "University of Melbourne", "University of Sydney",

    "University of New South Wales (UNSW)", "Monash University", "University of Queensland",
    "Tel Aviv University", "Technion - Israel Institute of Technology", "King Abdullah University of Science and Technology (KAUST)",
    "Khalifa University", "University of São Paulo", "National Autonomous University of Mexico (UNAM)",
    "University of Buenos Aires", "University of Cape Town", "University of the Witwatersrand",
    "Lomonosov Moscow State University", "Saint Petersburg State University", "Bauman Moscow State Technical University",
    "University of Copenhagen", "Aarhus University", "Lund University", "Uppsala University",
    "University of Helsinki", "Aalto University", "University of Oslo", "Norwegian University of Science and Technology (NTNU)",
    "KU Leuven", "Ghent University", "University of Amsterdam", "Leiden University",
    "Utrecht University", "Wageningen University & Research", "University of Vienna", "Technical University of Vienna",
    "University of Zurich", "University of Geneva", "Trinity College Dublin", "University College Dublin",
    "University of Auckland", "Fayoum University", "South Valley University", "Beni-Suef University",
    "Minia University", "Sohag University", "Aswan University", "Damanhour University", "Sadat City University",
    "Matrouh University", "New Valley University", "Luxor University", "Arish University"
]

roles = [
    "Software Engineer", "Data Scientist", "ML Engineer", "Backend Developer", "Frontend Developer",
    "Cloud Architect", "DevOps Engineer", "Research Assistant", "Full Stack Developer",
    "Data Analyst", "Security Analyst", "Network Engineer", "Systems Administrator",
    "QA Engineer", "AI Researcher", "Product Manager", "UI/UX Designer", "Database Administrator",
    "Technical Lead", "Junior Software Engineer", "Senior Software Engineer", "Principal Software Engineer",
    "Staff Software Engineer", "Engineering Manager", "Site Reliability Engineer (SRE)",
    "Solutions Architect", "Data Engineer", "Business Intelligence (BI) Developer",

    "Mobile Developer (iOS)", "Mobile Developer (Android)", "Embedded Systems Engineer", "Firmware Engineer",
    "Game Developer", "Graphics Engineer", "Automation Engineer", "Test Automation Engineer",
    "Software Development Engineer in Test (SDET)", "Security Engineer", "Application Security Engineer",
    "Cloud Security Engineer", "Cybersecurity Consultant", "Penetration Tester", "Incident Responder",
    "Network Architect", "Systems Engineer", "Cloud Engineer", "Cloud Consultant",
    "DevOps Consultant", "Release Engineer", "Build Engineer", "Infrastructure Engineer",
    "Platform Engineer", "Database Engineer", "SQL Developer", "Data Warehouse Engineer",

    "Machine Learning Scientist", "Applied Scientist", "Research Scientist", "Computer Vision Engineer",
    "NLP Engineer", "Robotics Engineer", "Quantitative Analyst", "Financial Engineer",
    "Technical Program Manager (TPM)", "Technical Project Manager", "IT Manager", "Director of Engineering",
    "VP of Engineering", "Chief Technology Officer (CTO)", "UI Engineer", "UX Engineer",
    "UX Researcher", "Product Designer", "Interaction Designer", "Visual Designer",
    "Scrum Master", "Agile Coach", "IT Support Specialist", "Help Desk Technician", "Systems Analyst",
    "Business Analyst", "Technical Writer", "Technical Evangelist", "Developer Advocate",

    "Sales Engineer", "Pre-Sales Engineer", "Post-Sales Engineer", "Field Engineer",
    "Customer Success Engineer", "Support Engineer", "Implementation Consultant", "Integration Engineer",
    "IT Consultant", "Technology Consultant", "Data Architect", "Enterprise Architect",
    "Hardware Engineer", "ASIC Design Engineer", "FPGA Engineer", "Validation Engineer",
    "Verification Engineer", "Control Systems Engineer", "Telecommunications Engineer",
    "Quality Assurance Analyst", "Manual QA Tester", "Performance Engineer",
    "Technical Recruiter", "IT Auditor", "Compliance Analyst", "Data Privacy Engineer",
    "Digital Forensics Analyst", "SOC Analyst", "Threat Hunter", "Cryptographer",

    "Machine Learning Operations (MLOps) Engineer", "AI Product Manager", "Blockchain Developer",
    "Smart Contract Developer", "Quantum Computing Scientist", "Growth Hacker",
    "E-commerce Specialist", "Webmaster", "CRM Developer", "ERP Consultant",

    "BI Analyst", "Data Governor", "Data Steward", "Chief Data Officer (CDO)",
    "Chief Information Officer (CIO)", "Chief Information Security Officer (CISO)",

    "Associate Product Manager", "Senior Product Manager", "Group Product Manager",
    "Lead Product Designer", "Senior UX Researcher", "Lead Data Scientist", "Principal Data Scientist",
    "Senior Data Engineer", "Lead DevOps Engineer", "Principal Cloud Architect", "Distinguished Engineer",
    "Software Architect", "Technical Consultant", "Analytics Engineer", "Decision Scientist",
    "Bioinformatics Scientist", "Computational Biologist", "Game Designer", "Level Designer",
    "Unity Developer", "Unreal Engine Developer", "VR/AR Developer", "Full Stack Engineer"
]

companies = [
    "Vodafone", "Microsoft", "IBM", "Valeo", "Dell", "Instabug", "Google", "Orange",
    "Amazon", "Meta", "Apple", "Oracle", "SAP", "Etisalat", "Raya Corp", "e-finance",
    "Fawry", "Bosta", "Swvl", "ProGlove", "Siemens", "Intel", "NVIDIA", "AMD", "Qualcomm",
    "Cisco", "HP", "Lenovo", "Samsung", "Huawei", "Sony", "Panasonic", "Accenture",
    "Capgemini", "Atos", "DXC Technology", "NTT Data", "Cognizant", "Infosys", "Wipro",
    "TCS", "HCL Technologies", "Salesforce", "Adobe", "VMware", "Broadcom", "ServiceNow",
    "Intuit", "Autodesk", "Atlassian", "Splunk", "Palo Alto Networks", "Fortinet",

    "CrowdStrike", "Zscaler", "Snowflake", "Datadog", "MongoDB", "Elastic", "Twilio",
    "Stripe", "PayPal", "Square (Block)", "Shopify", "Uber", "Lyft", "Airbnb", "Netflix",
    "Spotify", "Twitter (X)", "LinkedIn", "TikTok (ByteDance)", "Tencent", "Alibaba",
    "Baidu", "JD.com", "Meituan", "Ericsson", "Nokia", "Rakuten", "SoftBank",
    "Goldman Sachs", "J.P. Morgan", "Morgan Stanley", "Citadel", "Jane Street", "Two Sigma",
    "Bloomberg", "Thomson Reuters", "Booking.com", "Expedia Group", "Trivago",

    "Delivery Hero (Talabat)", "Glovo", "Careem", "Souq.com (Amazon EG)", "Jumia",
    "Noon", "Vezeeta", "Paymob", "Thndr", "MaxAB", "Trella", "Halan", "Capiter",
    "Brantu", "Homzmart", "Rabbit", "Sary", "PayTabs", "Tamara", "Tabby",
    "MNT-Halan", "Khazna", "BasharSoft (Wuzzuf)", "Eventtus", "Elmenus", "GoodsMart",
    "SWVL", "Robusta", "Sequel", "Affectiva", "Trella", "Dsquares", "ITWorx",
    "Intouch.com", "Systems Engineering of Egypt (SEE)", "Giza Systems", "Link Development",
    "ArpuPlus", "Target", "Walmart Labs", "The Home Depot", "Ford", "General Motors",
    "BMW", "Mercedes-Benz", "Bosch", "Continental", "Thales", "Dassault Systèmes",
    "Schlumberger", "Baker Hughes", "General Electric", "Philips", "Johnson & Johnson",
    "Roche", "Novartis", "Electronic Arts (EA)", "Activision Blizzard", "Take-Two Interactive",
    "Ubisoft", "Riot Games", "Epic Games", "Unity Technologies", "Roblox"
]

techs = [
    "Python", "TensorFlow", "PyTorch", "Flask", "React", "AWS", "Docker", "Kubernetes", "SQL",
    "Java", "JavaScript", "C++", "Go", "Rust", "Node.js", "Angular", "Vue.js", "Django",
    "Spring Boot", "Google Cloud Platform (GCP)", "Microsoft Azure", "Terraform",
    "Ansible", "Jenkins", "Git", "MongoDB", "PostgreSQL", "Redis", "Kafka", "Spark", "Hadoop",
    "Tableau", "Power BI", "Scikit-learn", "Keras", "FastAPI", "C#", "Swift", "Kotlin",
    "PHP", "Ruby", "TypeScript", "HTML5", "CSS3", "Sass", "LESS", "jQuery", "Bootstrap",
    "Next.js", "Gatsby", "Nuxt.js", "Svelte", "Express.js", "Koa.js", "Ruby on Rails",
    "Laravel", "Symfony", "ASP.NET Core", "Hibernate", "SQLAlchemy", "MySQL", "Microsoft SQL Server",
    "Oracle Database", "SQLite", "Cassandra", "Couchbase", "DynamoDB", "Firebase",
    "Elasticsearch", "Solr", "GraphQL", "REST APIs", "gRPC", "RabbitMQ", "ActiveMQ",
    "ZeroMQ", "Nginx", "Apache HTTP Server", "HAProxy", "Linux", "Unix", "Windows Server",
    "Bash", "PowerShell", "VMware", "VirtualBox", "Vagrant", "Packer", "Puppet", "Chef",
    "SaltStack", "GitLab CI", "GitHub Actions", "CircleCI", "Travis CI", "Prometheus",
    "Grafana", "Zabbix", "Nagios", "Datadog", "Splunk", "ELK Stack", "JIRA", "Confluence",
    "Trello", "Slack", "Microsoft Teams", "OpenCV", "Pillow", "Numpy", "Pandas",
    "Matplotlib", "Seaborn", "Plotly", "D3.js", "Airflow", "Luigi", "Prefect", "dbt",
    "Snowflake", "Redshift", "BigQuery", "Databricks", "Presto", "Hive", "Flink", "Storm",
    "Jupyter Notebook", "Google Colab", "VS Code", "IntelliJ IDEA", "PyCharm", "Eclipse",
    "Android Studio", "Xcode", "Unity", "Unreal Engine", "Blender", "Figma", "Sketch",
    "Adobe XD", "InVision", "Zeplin", "Selenium", "Cypress", "Jest", "Mocha", "Pytest",
    "JUnit", "TestNG", "Postman", "Swagger (OpenAPI)", "OAuth 2.0", "JWT", "SAML", "OpenID Connect"
]

projects = [
    "chatbot", "recommendation engine", "image segmentation model", "fraud detection system",
    "price prediction dashboard", "DevOps automation pipeline", "real-time data pipeline",
    "e-commerce platform", "social media analytics tool", "sentiment analysis NLP engine",
    "customer churn prediction model", "automated code deployment system",
    "cloud-native microservices application", "IoT data processing system",
    "supply chain optimization algorithm", "object detection system for autonomous vehicles",
    "time series forecasting for stock prices", "credit scoring model", "customer lifetime value prediction",
    "market basket analysis system", "A/B testing framework", "search engine for a specific domain",
    "content management system (CMS)", "customer relationship management (CRM) system",
    "enterprise resource planning (ERP) module", "ride-sharing application", "food delivery service",
    "online learning platform", "hotel booking website", "flight reservation system",
    "medical image analysis tool", "genomic data analysis pipeline", "drug discovery platform",
    "patient monitoring system", "electronic health record (EHR) system", "log analysis platform",
    "distributed file system", "in-memory database", "custom programming language compiler",
    "operating system kernel module", "network traffic monitoring tool", "penetration testing toolkit",
    "vulnerability scanner", "blockchain-based voting system", "decentralized finance (DeFi) application",
    "NFT marketplace", "3D rendering engine", "physics simulation for a game",
    "procedural content generation algorithm", "virtual reality (VR) training simulation",
    "augmented reality (AR) mobile app", "voice assistant application", "speech-to-text transcription service",
    "machine translation system", "text summarization tool", "question-answering system",
    "facial recognition system", "emotion detection from video feeds", "gesture recognition interface",
    "anomaly detection in manufacturing", "predictive maintenance system for machinery",
    "energy consumption forecasting model", "traffic flow prediction system", "smart home automation hub",

    "personal finance management app", "portfolio optimization tool", "high-frequency trading bot",
    "spam email filter", "malware detection system", "network intrusion detection system",
    "automated data quality checker", "ETL pipeline for data warehousing", "serverless data lake",
    "CI/CD pipeline for machine learning models (MLOps)", "infrastructure as code (IaC) setup for a cloud environment",
    "container orchestration platform for a microservices architecture", "API gateway implementation",
    "service mesh configuration", "load testing framework", "automated performance monitoring dashboard",
    "static code analysis tool", "bug tracking system", "online collaborative whiteboard",
    "video conferencing application", "real-time chat application", "music streaming service",
    "podcast publishing platform", "news aggregation website", "online forum or community board",
    "job portal application", "resume parsing system", "employee management system",
    "inventory management system", "point of sale (POS) system", "appointment scheduling system",
    "event ticketing platform", "customer feedback analysis system", "brand reputation monitor",
    "web scraping and data aggregation tool", "data visualization library", "interactive map application",
    "route planning algorithm for logistics", "facial animation system", "style transfer model for images",
    "generative adversarial network (GAN) for art creation", "reinforcement learning agent for a game",
    "personalized advertising engine", "dynamic pricing model", "automated essay grading system",
    "code completion tool for an IDE", "dependency management tool", "license plate recognition system",
    "document scanner and OCR application", "handwriting recognition model",
    "biometric authentication system", "smart contract for supply chain", "secure multi-party computation protocol",
    "homomorphic encryption library", "data anonymization pipeline", "federated learning framework",
    "quantum computing algorithm simulation", "weather forecasting model", "natural disaster prediction system",
    "wildfire detection from satellite imagery", "crop yield prediction model", "soil moisture sensor network",
    "smart irrigation system", "AI-powered personal tutor", "language learning application",
    "adaptive testing platform", "music composition AI", "sports analytics dashboard",
    "player performance prediction model", "legal document analysis tool", "automated contract review system"
]

skills = [
    "machine learning", "deep learning", "computer vision", "NLP", "data visualization",
    "cloud computing", "CI/CD", "API design", "distributed systems", "microservices architecture",
    "agile methodologies", "data structures and algorithms", "database management",
    "network security", "containerization", "orchestration", "big data analytics",
    "system design", "software development life cycle (SDLC)", "test-driven development (TDD)",
    "behavior-driven development (BDD)", "object-oriented programming (OOP)",
    "functional programming", "RESTful APIs", "GraphQL", "web sockets", "message queues",
    "stream processing", "batch processing", "ETL processes", "data modeling",
    "data warehousing", "database normalization", "SQL optimization", "NoSQL databases",
    "scalability", "high availability", "fault tolerance", "disaster recovery",
    "performance tuning", "load balancing", "caching strategies", "version control (Git)",
    "infrastructure as code (IaC)", "monitoring and logging", "alerting and on-call",
    "incident management", "penetration testing", "vulnerability assessment",
    "identity and access management (IAM)", "encryption", "secure coding practices",
    "threat modeling", "scrum", "kanban", "lean development", "product management",
    "A/B testing", "user experience (UX) design", "user interface (UI) design",
    "wireframing", "prototyping", "responsive design", "mobile-first development",
    "cross-browser compatibility", "web accessibility (WCAG)", "unit testing",
    "integration testing", "end-to-end testing", "performance testing", "static code analysis",
    "code review", "debugging", "profiling", "memory management", "concurrency",
    "multithreading", "asynchronous programming", "operating systems (Linux/Unix)",
    "shell scripting", "command-line interface (CLI)", "networking protocols (TCP/IP, HTTP)",
    "DNS", "firewalls", "VPNs", "reinforcement learning", "generative models (GANs, VAEs)",
    "transformers", "attention mechanisms", "explainable AI (XAI)", "federated learning",
    "MLOps", "model deployment", "model monitoring", "feature engineering",
    "hyperparameter tuning", "statistical analysis", "probability theory", "linear algebra",
    "calculus", "optimization", "time series analysis", "survival analysis", "bayesian inference",
    "data mining", "web scraping", "problem-solving", "critical thinking",
    "communication", "teamwork", "leadership", "mentoring", "technical writing",
    "documentation", "stakeholder management", "project management", "time management",
    "domain-driven design (DDD)", "serverless architecture", "event-driven architecture",
    "site reliability engineering (SRE)", "chaos engineering", "automation",
    "command and control (C2) frameworks", "reverse engineering", "malware analysis",
    "digital forensics", "cryptography", "blockchain", "smart contracts",
    "system architecture", "enterprise architecture", "solution architecture", "data architecture",
    "prompt engineering", "large language models (LLMs)", "vector databases",
    "retrieval-augmented generation (RAG)", "fine-tuning models", "quantitative analysis",
    "risk management", "business intelligence", "cloud security", "application security",
    "data privacy", "regulatory compliance (GDPR, HIPAA)", "AIOps"
]

certs = [
    "AWS Certified Machine Learning - Specialty", "Google Cloud Professional Cloud Architect",
    "TensorFlow Developer Certificate", "Microsoft Certified: Azure Administrator Associate",
    "Udacity Data Scientist Nanodegree", "Coursera Deep Learning Specialization",
    "Certified Information Systems Security Professional (CISSP)", "Certified Ethical Hacker (CEH)",
    "Kubernetes Certified Administrator (CKA)", "Professional Scrum Master (PSM I)",
    "AWS Certified Solutions Architect - Associate", "Google Cloud Professional Data Engineer",
    "Microsoft Certified: Azure AI Engineer Associate", "AWS Certified Developer - Associate",
    "AWS Certified SysOps Administrator - Associate", "AWS Certified Solutions Architect - Professional",
    "AWS Certified DevOps Engineer - Professional", "AWS Certified Security - Specialty",
    "AWS Certified Advanced Networking - Specialty", "AWS Certified Data Analytics - Specialty",
    "AWS Certified Database - Specialty", "Google Cloud Associate Cloud Engineer",
    "Google Cloud Professional Cloud Developer", "Google Cloud Professional Cloud DevOps Engineer",
    "Google Cloud Professional Cloud Security Engineer", "Google Cloud Professional Cloud Network Engineer",
    "Google Cloud Professional Collaboration Engineer", "Google Cloud Professional Machine Learning Engineer",
    "Microsoft Certified: Azure Developer Associate", "Microsoft Certified: Azure Security Engineer Associate",
    "Microsoft Certified: Azure Data Scientist Associate", "Microsoft Certified: Azure Data Engineer Associate",
    "Microsoft Certified: DevOps Engineer Expert", "Microsoft Certified: Azure Solutions Architect Expert",
    "Microsoft Certified: Cybersecurity Architect Expert", "Certified Information Security Manager (CISM)",
    "Certified in Risk and Information Systems Control (CRISC)", "Certified Information Systems Auditor (CISA)",
    "CompTIA Security+", "CompTIA Network+", "CompTIA A+", "CompTIA CySA+", "CompTIA PenTest+",
    "CompTIA Cloud+", "GIAC Security Essentials (GSEC)", "GIAC Certified Incident Handler (GCIH)",
    "GIAC Certified Penetration Tester (GPEN)", "Offensive Security Certified Professional (OSCP)",
    "Cisco Certified Network Associate (CCNA)", "Cisco Certified Network Professional (CCNP) Enterprise",
    "Cisco Certified CyberOps Associate", "Certified Kubernetes Application Developer (CKAD)",
    "Certified Kubernetes Security Specialist (CKS)", "Red Hat Certified System Administrator (RHCSA)",
    "Red Hat Certified Engineer (RHCE)", "Oracle Certified Professional, Java SE Programmer",
    "Oracle Certified Professional, MySQL Database Administrator", "Oracle Cloud Infrastructure Foundations Associate",
    "PMI Project Management Professional (PMP)", "Certified Associate in Project Management (CAPM)",
    "PMI Agile Certified Practitioner (PMI-ACP)", "Certified ScrumMaster (CSM)",
    "Certified Scrum Product Owner (CSPO)", "SAFe Agilist (SA)", "ITIL Foundation Certificate",
    "HashiCorp Certified: Terraform Associate", "HashiCorp Certified: Vault Associate",
    "HashiCorp Certified: Consul Associate", "Databricks Certified Data Engineer Associate",
    "Databricks Certified Data Engineer Professional", "Databricks Certified Machine Learning Associate",
    "Snowflake SnowPro Core Certification", "Cloudera Data Platform (CDP) Certified Administrator",
    "Certified Analytics Professional (CAP)", "Tableau Desktop Specialist",
    "Tableau Certified Data Analyst", "Microsoft Power BI Data Analyst Associate",
    "Alibaba Cloud Associate (ACA)", "Alibaba Cloud Professional (ACP)",
    "The Linux Foundation Certified System Administrator (LFCS)", "The Linux Foundation Certified Engineer (LFCE)",
    "Certified Cloud Security Professional (CCSP)", "Systems Security Certified Practitioner (SSCP)",
    "Certified in the Governance of Enterprise IT (CGEIT)", "GIAC Web Application Penetration Tester (GWAPT)",
    "GIAC Defensible Security Architecture (GDSA)", "Certified Threat Intelligence Analyst (CTIA)",
    "Computer Hacking Forensic Investigator (CHFI)", "AWS Certified Cloud Practitioner",
    "Microsoft 365 Certified: Fundamentals", "Microsoft Certified: Security, Compliance, and Identity Fundamentals",
    "Microsoft Certified: Azure Data Fundamentals", "Microsoft Certified: Azure AI Fundamentals",
    "Google Cloud Digital Leader", "IBM Certified AI Professional", "SAS Certified Data Scientist",
    "Certified Professional in Python Programming (PCPP)", "Certified Associate in Python Programming (PCAP)",
    "IIBA Certified Business Analysis Professional (CBAP)", "ISTQB Certified Tester Foundation Level",
    "ISTQB Certified Tester Advanced Level", "Certified UX Designer by Nielsen Norman Group (NN/g)",
    "Certified Product Manager (AIPMM)", "Pragmatic Institute Certified Product Manager",
    "Google UX Design Professional Certificate", "IBM Data Science Professional Certificate",
    "Meta Backend Developer Professional Certificate", "Meta Frontend Developer Professional Certificate",
    "Google Project Management Professional Certificate", "Google IT Support Professional Certificate",
    "Google Data Analytics Professional Certificate", "Certified AI & Machine Learning Engineer (Simplilearn)",
    "Full Stack Web Development Nanodegree (Udacity)", "Robotics Software Engineer Nanodegree (Udacity)",
    "Self-Driving Car Engineer Nanodegree (Udacity)", "Deep Reinforcement Learning Nanodegree (Udacity)",
    "Computer Vision Nanodegree (Udacity)", "NLP Nanodegree (Udacity)", "Data Engineer Nanodegree (Udacity)",
    "Cloud DevOps Engineer Nanodegree (Udacity)", "Certified Information Privacy Professional (CIPP)",
    "Certified Information Privacy Manager (CIPM)", "Certified Information Privacy Technologist (CIPT)",
    "Certified Ethical Hacker (Master)", "Licensed Penetration Tester (Master)",
    "Certified Red Team Professional (CRTP)", "Certified Azure Red Team Professional (CARTP)",
    "eLearnSecurity Certified Professional Penetration Tester (eCPPT)", "eLearnSecurity Certified Web Application Penetration Tester (eWPT)",
    "GIAC Exploit Researcher and Advanced Penetration Tester (GXPN)", "GIAC Reverse Engineering Malware (GREM)",
    "GIAC Advanced Smartphone Forensics (GASF)", "Certified SAFe DevOps Practitioner",
    "Certified SAFe Architect", "Certified SAFe Product Owner/Product Manager",
    "Professional Cloud Solutions Architect (PCSA)", "Docker Certified Associate (DCA)",
    "Splunk Core Certified User", "Splunk Core Certified Power User", "Splunk Enterprise Certified Admin",
    "Splunk Enterprise Certified Architect"
]

templates = {
    "Education": [
        "Graduated with a {degree} in {major} from {university}.",
        "Earned a {degree} in {major} from {university}.",
        "Completed a {degree} in {major} at {university}.",
        "Obtained a {degree} in {major} from {university}.",
        "Achieved a {degree} in {major} at {university}.",
        "Awarded a {degree} in {major} from {university}.",
        "{university} conferred upon me a {degree} in {major}.",
        "A proud graduate of {university} with a {degree} in {major}.",
        "Holds a {degree} in {major} from the esteemed {university}.",
        "My academic background includes a {degree} in {major} from {university}.",
        "Specialized in {major} during my {degree} studies at {university}.",
        "Focused on {major} while pursuing a {degree} at {university}.",
        "Completed my {degree} at {university}, with a concentration in {major}.",
        "Graduated with honors from {university} with a {degree} in {major}.",
        "Earned a {degree} in {major}, graduating cum laude from {university}.",
        "My {degree} in {major} from {university} included a thesis on {project}.",
        "Completed a research-focused {degree} in {major} at {university}.",
        "As part of my {degree} in {major} from {university}, I specialized in {skill}.",
        "Acquired a strong foundation in {major} through my {degree} program at {university}.",
        "The curriculum for my {degree} in {major} at {university} covered {skill1} and {skill2}.",
        "Excelled in the {major} program at {university}, culminating in a {degree}.",
        "A {university} alumnus, holding a {degree} in {major}.",
        "Finished my {degree} in {major} at {university} in {year}.",
        "Secured a {degree} in {major} from {university}, focusing on practical applications.",
        "My education at {university} provided me with a {degree} in {major}.",
        "Proudly holding a {degree} in {major} from {university}.",
        "My {degree} from {university} is in {major}.",
        "Completed postgraduate studies at {university} with a {degree} in {major}.",
        "My undergraduate {degree} in {major} was completed at {university}.",
        "A graduate of the {major} department at {university} with a {degree}.",
        "Successfully obtained a {degree} in {major} from {university}.",
        "Earned my academic credentials, including a {degree} in {major}, from {university}.",
        "My formal education is a {degree} in {major} from {university}.",
        "Recipient of a {degree} in {major} from {university}'s School of Engineering.",
        "My studies at {university} led to a {degree} in {major}.",
        "Completed an intensive {degree} program in {major} at {university}.",
        "My academic journey at {university} concluded with a {degree} in {major}.",
        "I am a graduate of {university} with a {degree} in the field of {major}.",
        "Achieved academic excellence at {university}, earning a {degree} in {major}.",
        "My {degree} in {major} from {university} prepared me for a career in {field}.",
        "Graduated from {university}'s prestigious {major} program with a {degree}.",
        "Completed all requirements for a {degree} in {major} at {university}.",
        "Holder of a {degree} in {major}, awarded by {university}.",
        "My time at {university} resulted in a {degree} in {major}.",
        "Successfully defended my thesis for a {degree} in {major} at {university}.",
        "My professional qualifications are built upon a {degree} in {major} from {university}.",
        "A {degree} holder in {major} from {university}.",
        "Formally educated at {university}, where I received my {degree} in {major}.",
        "My academic qualifications include a {degree} in {major} from {university}.",
        "Gained a comprehensive understanding of {major} during my {degree} at {university}.",
        "My educational background is a {degree} in {major} from {university}.",
        "Completed a rigorous {degree} program in {major} at {university}.",
        "At {university}, I pursued and was awarded a {degree} in {major}.",
        "My scholastic achievements include a {degree} in {major} from {university}.",
        "Proudly represent {university} as a graduate with a {degree} in {major}.",
        "My academic training at {university} culminated in a {degree} in {major}.",
        "Awarded a {degree} with a specialization in {major} from {university}.",
        "Completed a {degree} in {major} with a focus on {sub_field} at {university}.",
        "Graduated with distinction, holding a {degree} in {major} from {university}.",
        "Earned a {degree} in {major} through a combination of coursework and research at {university}.",
        "My {degree} from {university} provided deep insights into {major}.",
        "At {university}, I earned my {degree} in {major}, a pivotal step in my career.",
        "A {degree} in {major} from {university} launched my professional journey.",
        "Secured my {degree} in {major} from {university}, a leader in the field.",
        "I am a {university} graduate, where I obtained my {degree} in {major}.",
        "My academic record shows a {degree} in {major} from {university}.",
        "The foundation of my expertise is a {degree} in {major} from {university}.",
        "Completed a {degree} in {major} at {university}, which included projects on {topic}.",
        "Achieved a {degree} in {major} from {university} with a GPA of {gpa}.",
        "My {degree} studies in {major} at {university} involved extensive lab work.",
        "Graduated from {university}'s competitive {major} program with a {degree}.",
        "My {degree} in {major} was conferred by {university} in {year}.",
        "As a student at {university}, I successfully completed my {degree} in {major}.",
        "My coursework for the {degree} in {major} at {university} included {course1}, {course2}.",
        "I hold a {degree} in {major}, a qualification I earned from {university}.",
        "My scholastic path led me to a {degree} in {major} from {university}.",
        "Proud to be an alumnus of {university} with a {degree} in {major}.",
        "Completed a demanding {degree} curriculum in {major} at {university}.",
        "My training includes a {degree} in {major} from {university}.",
        "Graduated top of my class from {university} with a {degree} in {major}.",
        "The {major} department at {university} awarded me a {degree}.",
        "My academic pursuits at {university} resulted in a {degree} in {major}.",

        "I am a holder of a {degree} in {major} from the renowned {university}.",
        "Successfully navigated the {major} program at {university} to earn a {degree}.",
        "My academic chapter at {university} was capped with a {degree} in {major}.",
        "Earned a {degree} in {major} from {university}, participating in {extracurricular_activity}.",
        "The {degree} I received from {university} was in the field of {major}.",
        "My {degree} in {major} from {university} was a multidisciplinary program.",
        "Graduated from {university} after completing the {degree} program in {major}.",
        "I possess a {degree} in {major} that I obtained from {university}.",
        "My professional development began with a {degree} in {major} from {university}.",
        "Achieved a {degree} in {major} at {university}, gaining skills in {skill}.",
        "Completed my formal education at {university} with a {degree} in {major}.",
        "The {degree} in {major} from {university} provided me with a solid theoretical base.",
        "My academic credentials from {university} are centered around my {degree} in {major}.",
        "I am academically qualified with a {degree} in {major} from {university}."
    ],
    "Experience": [
        "Worked as a {role} at {company} using {tech}.",
        "Served as a {role} at {company} for {yrs} years.",
        "Interned at {company} as a {role}, contributing to {project}.",
        "As a {role} at {company}, I developed solutions using {tech}.",
        "Held the position of {role} at {company}, where I specialized in {tech}.",
        "Gained valuable experience as a {role} at {company}, working with {tech1} and {tech2}.",
        "Employed by {company} as a {role}, focusing on {skill}.",
        "At {company}, I took on the responsibilities of a {role}, delivering {project}.",
        "My tenure at {company} as a {role} involved extensive use of {tech}.",
        "Contributed to {company}'s success as a {role} by implementing {project}.",
        "Led a team of {num} as a {role} at {company} to build a {project}.",
        "Engineered and maintained systems as a {role} at {company} using {tech}.",
        "As a {role} at {company}, I was responsible for the design and development of {project}.",
        "Collaborated with cross-functional teams at {company} in my capacity as a {role}.",
        "Optimized application performance by {percentage}% as a {role} at {company}.",
        "Architected scalable solutions using {tech} in my role as {role} at {company}.",
        "My professional journey includes working as a {role} at {company}.",
        "At {company}, I served as a {role}, where I honed my skills in {skill}.",
        "As a key member of the team at {company}, I worked as a {role} on the {project}.",
        "My role as {role} at {company} involved automating processes with {tech}.",
        "Successfully delivered multiple projects as a {role} at {company}.",
        "Functioned as a {role} at {company}, improving system reliability with {tech}.",
        "In my position as {role} at {company}, I managed the full lifecycle of {project}.",
        "Was an integral part of the {team} team at {company}, serving as a {role}.",
        "Advanced from {junior_role} to {role} at {company} in {yrs} years.",
        "At {company}, my responsibilities as a {role} included {responsibility1} and {responsibility2}.",
        "Built and deployed applications on {platform} as a {role} at {company}.",
        "My experience at {company} as a {role} centered on {skill} and {tech}.",
        "As a {role} for {company}, I played a pivotal role in the {project} initiative.",
        "Drove innovation at {company} as a {role} by introducing {tech}.",
        "Mentored junior developers in my capacity as a {role} at {company}.",
        "Reduced operational costs by {amount} as a {role} at {company} by implementing {solution}.",
        "As a {role} at {company}, I worked extensively with the {tech} stack.",
        "Pioneered the use of {tech} at {company} during my time as a {role}.",
        "My professional background includes a {yrs}-year stint as a {role} at {company}.",
        "At {company}, I was a {role} tasked with enhancing the {product} feature set.",
        "Successfully managed and executed {project} as a {role} at {company}.",
        "As a {role} at {company}, I applied my {skill} expertise to solve complex problems.",
        "Contributed to open-source projects while working as a {role} at {company}.",
        "Designed and implemented APIs for {project} as a {role} at {company}.",
        "In my role as {role} at {company}, I was in charge of the {tech} infrastructure.",
        "My work as a {role} at {company} resulted in a significant improvement in {metric}.",
        "As a {role} at {company}, I was on the front lines of developing {product}.",
        "Grew into a leadership position as a {role} at {company}.",
        "Was responsible for code quality and testing as a {role} at {company}.",
        "My professional experience was enriched by my work as a {role} at {company}.",
        "At {company}, my duties as a {role} included maintaining and upgrading legacy systems.",
        "Spearheaded the migration to {tech} as a {role} at {company}.",
        "As a {role} at {company}, I facilitated agile ceremonies and sprint planning.",
        "My contributions as a {role} at {company} were recognized with {award}.",
        "Joined {company} as a {role} and quickly became a key contributor to {project}.",
        "My work experience includes a contract position as a {role} at {company}.",
        "At {company}, I worked as a {role} within a fast-paced, agile environment.",
        "As a {role} at {company}, I focused on building user-centric applications with {tech}.",
        "Helped scale the {product} at {company} in my position as {role}.",
        "My time as a {role} at {company} was marked by successful project deliveries.",
        "As a {role} at {company}, I implemented robust security measures using {tech}.",
        "Championed best practices in {skill} as a {role} at {company}.",
        "My career began at {company} where I worked as a {role}.",
        "As a {role} at {company}, I had the opportunity to work on cutting-edge {tech}.",
        "At {company}, I was the lead {role} for the {project}, overseeing all development stages.",
        "In my capacity as a {role} at {company}, I conducted code reviews and provided feedback.",
        "My professional skills were sharpened during my employment as a {role} at {company}.",
        "As a {role} at {company}, I was tasked with debugging and resolving critical production issues.",
        "I was a {role} at {company}, where my primary focus was on {area}.",
        "Developed high-quality software as a {role} at {company}, adhering to industry standards.",
        "My role of {role} at {company} required a deep understanding of {tech} and {skill}.",
        "At {company}, I excelled as a {role}, contributing to a {percentage}% growth in user engagement.",
        "As a {role} at {company}, I worked on the full software development lifecycle.",
        "My professional history includes serving as a {role} for {company}.",
        "At {company}, I was promoted to {role} after demonstrating expertise in {skill}.",
        "As a {role} at {company}, I collaborated with product managers to define feature requirements.",
        "I gained hands-on experience in {tech} as a {role} during my internship at {company}.",
        "My responsibilities as a {role} at {company} extended to CI/CD pipeline management.",
        "As a {role} at {company}, I was a key player in the transition to a microservices architecture.",
        "My position at {company} was {role}, where I utilized {tech} for data analysis.",
        "I was part of the core engineering team at {company}, working as a {role}.",
        "As a {role} at {company}, I improved data processing speeds by {factor}x.",
        "My experience as a {role} at {company} involved working with large-scale distributed systems.",
        "At {company}, I held the title of {role} and was responsible for {key_task}.",
        "As a {role} at {company}, I built reusable components and libraries for future use.",
        "My career includes a significant contribution as a {role} at {company}.",
        "At {company}, I was a {role} on a team that launched the award-winning {product}.",
        "In the role of {role} at {company}, I leveraged {tech} to create data visualizations.",
        "As a {role} at {company}, I was instrumental in architecting their cloud infrastructure.",
        "My professional path led me to {company} where I served as a {role}.",
        "At {company}, I thrived as a {role}, tackling challenges in {domain}.",
        "As a {role} at {company}, I wrote and maintained technical documentation.",
        "My work at {company} as a {role} was centered on enhancing user experience.",
        "I was employed as a {role} at {company}, focusing on performance and scalability.",
        "As a {role} at {company}, I translated business requirements into technical solutions.",
        "My time at {company} as a {role} was a period of significant professional growth.",
        "At {company}, as a {role}, I helped to establish the company's technical vision.",
        "In my former role as {role} at {company}, I worked with {tech} to analyze big data.",
        "As a {role} at {company}, I was recognized for my problem-solving skills.",
        "My background includes a successful tenure as a {role} at {company}."
    ],
    "Projects": [
        "Developed a {project} using {tech}.",
        "Built and deployed a {project} using {tech1} and {tech2}.",
        "Engineered a {project} leveraging a {tech} stack.",
        "Created a {project} for {purpose}.",
        "Architected a scalable {project} on {platform}.",
        "Led the development of a {project} from concept to completion.",
        "Contributed to an open-source {project} by implementing {feature}.",
        "Implemented a {project} that improved {metric} by {percentage}%.",
        "Designed the backend for a {project} using {tech}.",
        "Constructed a {project} as part of a university coursework.",
        "My portfolio includes a {project} built with {tech}.",
        "Successfully launched a {project} which now serves {num} users.",
        "As a personal challenge, I built a {project} utilizing {skill}.",
        "Managed the end-to-end lifecycle of a {project}.",
        "Sole developer of a {project} which demonstrates my skills in {tech}.",
        "Collaborated with a team to deliver a complex {project}.",
        "The highlight of my work is a {project} that solves {problem}.",
        "Published a {project} on GitHub, showcasing my proficiency in {tech}.",
        "This {project} was built to demonstrate the application of {skill}.",
        "Engineered a real-time {project} with {tech1} and {tech2}.",
        "My capstone {project} was a {description} model built with {tech}.",
        "Developed a proof-of-concept {project} for {company}.",
        "Built a {project} that processes and visualizes large datasets.",
        "Created a full-stack {project} with a {tech1} frontend and {tech2} backend.",
        "This {project} automates the process of {process_name}.",
        "I have hands-on experience building a {project} with a microservices architecture.",
        "My work on the {project} involved API design and integration.",
        "The {project} I built received positive feedback for its intuitive UI/UX.",
        "This {project} was a deep dive into the world of {domain}.",
        "Refactored a legacy {project}, improving its performance and maintainability.",
        "Developed a mobile-responsive {project} using {tech}.",
        "This {project} leverages machine learning to {outcome}.",
        "Created a secure {project} with a focus on data privacy.",
        "The technical stack for my {project} includes {tech1}, {tech2}, and {tech3}.",
        "My {project} involves complex data manipulation using {tech}.",
        "This {project} is a practical implementation of {algorithm} theory.",
        "I was responsible for the database schema design for the {project}.",
        "The {project} was deployed on {platform} using a CI/CD pipeline.",
        "My passion for {field} led me to create this {project}.",
        "This {project} showcases my ability to write clean, efficient code in {tech}.",
        "I designed and built the infrastructure for this {project} on {cloud_provider}.",
        "This {project} integrates with several third-party services via APIs.",
        "Developed a {project} as a freelancer for {client}.",
        "This {project} was my entry for the {hackathon_name} hackathon.",
        "My {project} uses {tech} to provide real-time analytics.",
        "This {project} features a custom-built {component} using {tech}.",
        "I took the initiative to start and complete this {project} independently.",
        "The goal of this {project} was to explore the capabilities of {tech}.",
        "This {project} is a demonstration of my skills in {skill1} and {skill2}.",
        "I have documented the architecture and code of my {project} extensively.",
        "This {project} passed all unit and integration tests with {percentage}% coverage.",
        "My {project} has been featured on {platform_or_blog}.",
        "This {project} was developed following Agile methodologies.",
        "The core functionality of this {project} is {functionality_description}.",
        "I optimized the performance of this {project}, reducing load times significantly.",
        "This {project} is an example of my ability to learn and apply new technologies like {tech}.",
        "I built this {project} to address a personal need for {purpose}.",
        "The data for this {project} is sourced from {data_source}.",
        "This {project} includes a user authentication system built with {tech}.",
        "My work on this {project} shows my understanding of software design principles.",
        "This {project} is containerized using {tech} for easy deployment.",
        "I created a comprehensive test suite for this {project}.",
        "The {project} has a clean and modern user interface designed by me.",
        "This {project} applies advanced algorithms to {domain}.",
        "I was the main contributor to the success of this {project}.",
        "This {project} is a command-line tool built with {tech}.",
        "The challenges in building this {project} included {challenge1} and {challenge2}.",
        "My {project} is a web application that provides {service}.",
        "This {project} adheres to the best practices of {field}.",
        "I am proud of this {project} because it taught me {lesson}.",
        "The source code for my {project} is available for review.",
        "This {project} processes data in batches using {tech}.",
        "I built the RESTful API for this {project} from scratch.",
        "This {project} required a deep dive into {specific_topic}.",
        "My {project} provides a practical solution to {real_world_problem}.",
        "This {project} is designed to be highly available and fault-tolerant.",
        "I implemented the {feature} feature in this {project}, which was a major undertaking.",
        "This {project} showcases my problem-solving abilities.",
        "The architecture of this {project} follows the {pattern_name} pattern.",
        "I have presented this {project} at {event_or_meetup}.",
        "This {project} is a testament to my dedication and passion for technology.",
        "I single-handedly developed the frontend and backend for this {project}.",
        "This {project} is a tool designed to help developers with {task}.",
        "My {project} is currently in its {version} version, with ongoing improvements.",
        "The user feedback for this {project} has been overwhelmingly positive.",
        "This {project} was an academic exercise in exploring {concept}.",
        "I am actively maintaining and adding new features to this {project}.",
        "This {project} demonstrates my ability to deliver a finished product.",
        "I built this {project} with scalability in mind from day one.",
        "The {project} involved data scraping, cleaning, and analysis.",
        "This {project} has a well-defined API for other services to consume.",
        "My {project} is an interactive web dashboard built with {tech}.",
        "This {project} was a collaborative effort, and my role was {my_role}.",
        "I have created a live demo for this {project} which can be accessed online.",
        "This {project} taught me the importance of {important_lesson}.",
        "The development of this {project} spanned over {duration}.",
        "I am the creator and maintainer of the {project}.",
        "This {project} is a clear demonstration of my technical capabilities.",
        "My {project} is an innovative solution for {industry}."
    ],
    "Skills": [
        "Proficient in {tech1}, {tech2}, and {tech3}.",
        "Experienced with {skill} for building scalable solutions.",
        "Strong grasp of {skill} and {tech}.",
        "Expert in {skill} with extensive experience in {tech}.",
        "Adept at {skill} and related technologies like {tech}.",
        "Skilled in {skill}, particularly with the {tech} framework.",
        "Well-versed in {skill} concepts and their practical application.",
        "Demonstrated expertise in {skill} through various projects.",
        "Advanced knowledge of {skill} and experience with {tech1} and {tech2}.",
        "Core competencies include {skill1}, {skill2}, and {skill3}.",
        "Possess strong skills in {skill}, which I have applied in professional settings.",
        "My technical skill set includes a deep understanding of {skill}.",
        "Familiar with {skill} and have a working knowledge of {tech}.",
        "I have hands-on experience with {skill} and {tech}.",
        "My primary area of expertise is {skill}.",
        "I am skilled in both frontend ({tech1}) and backend ({tech2}) development.",
        "My {skill} skills are complemented by my knowledge of {tech}.",
        "I have a proven track record of applying {skill} to solve business problems.",
        "My skills include designing and implementing systems using {tech}.",
        "I am proficient in database management with {tech1} and {tech2}.",
        "My expertise in {skill} allows me to develop efficient algorithms.",
        "I have a solid foundation in {skill} principles.",
        "I am constantly expanding my skills in {skill} and emerging technologies.",
        "My skill set is centered around {skill} and cloud platforms like {platform}.",
        "I possess excellent {skill} skills, crucial for {purpose}.",
        "My analytical skills are showcased by my proficiency in {tech}.",
        "I have developed strong {skill} capabilities throughout my career.",
        "My knowledge of {skill} is supported by my experience with {tech}.",
        "I am adept at using {tech} for {skill} tasks.",
        "My technical abilities include mastery of {skill} and {tech}.",
        "I have a special interest and developed skills in {skill}.",
        "I am an expert user of {tech} for {skill}.",
        "My skills in {skill} were critical to the success of {project}.",
        "I have a comprehensive understanding of the {skill} lifecycle.",
        "My programming skills are strongest in {tech1} and {tech2}.",
        "I have applied my {skill} skills in various domains, including {domain1} and {domain2}.",
        "I am confident in my ability to apply my {skill} knowledge to new challenges.",
        "My proficiency in {skill} is demonstrated by my {certification}.",
        "I have honed my {skill} skills over {yrs} years of experience.",
        "My technical repertoire includes {skill1}, {skill2}, and various {tech} tools.",
        "I am skilled in the art of {skill}, using tools like {tech}.",
        "I have a working proficiency in {skill} and {tech}.",
        "My strongest technical skill is {skill}.",
        "I have a passion for {skill} and stay up-to-date with the latest trends.",
        "I have cultivated a deep expertise in {skill}.",
        "My ability to use {tech} for {skill} sets me apart.",
        "I am highly skilled in {skill}, with a focus on performance optimization.",
        "My problem-solving skills are enhanced by my knowledge of {skill}.",
        "I have practical experience in implementing {skill} solutions.",
        "My technical skills are broad, covering {skill1}, {skill2}, and {skill3}.",
        "I am recognized for my skills in {skill} and attention to detail.",
        "My {skill} knowledge is both theoretical and practical.",
        "I have leveraged my {skill} expertise to lead successful projects.",
        "My skill set is a blend of {skill1} and {skill2}.",
        "I have a demonstrated ability to master new technologies and skills quickly.",
        "My experience has provided me with a unique skill set in {skill}.",
        "I am a {skill} enthusiast with hands-on experience.",
        "My {skill} abilities have been consistently praised by my peers.",
        "I have a talent for {skill}, particularly in complex scenarios.",
        "My skills are backed by a solid understanding of computer science fundamentals.",
        "I am proficient with a variety of tools for {skill}, including {tech}.",
        "My skills in {skill} have enabled me to create innovative solutions.",
        "I am always eager to apply my {skill} skills to challenging problems.",
        "My professional skills include {skill1}, {skill2}, and effective communication.",
        "I have a nuanced understanding of {skill} and its applications.",
        "My core strength lies in {skill} and {tech} integration.",
        "I am a practitioner of {skill}, with a focus on best practices.",
        "My command of {skill} is a key asset in my professional profile.",
        "I have a flair for {skill} and a passion for creating elegant solutions.",
        "I am well-equipped with {skill} skills needed for modern software development.",
        "My technical acumen is highlighted by my skills in {skill}.",
        "I have a deep and abiding interest in {skill}, which is reflected in my work.",
        "My skills in {skill} have been instrumental in my career progression.",
        "I have a certificate-proven skill in {skill}.",
        "My knowledge extends to various aspects of {skill}.",
        "I am proficient in the full stack of technologies required for {skill}.",
        "My skill set includes the ability to work with {tech} for {skill} purposes.",
        "I have a strong aptitude for {skill} and analytical thinking.",
        "My {skill} skills are at an expert level.",
        "I have a diverse set of skills, with a focus on {skill}.",
        "I am capable of handling all aspects of {skill} from design to deployment.",
        "My technical skills are current and relevant to the industry, especially in {skill}.",
        "I have a solid background in {skill}, reinforced by practical application.",
        "My skills have been tested and proven in high-pressure environments.",
        "I am a lifelong learner, currently improving my skills in {new_skill}.",
        "My expertise in {skill} is a result of years of dedicated practice.",
        "I am skilled in troubleshooting and debugging issues related to {skill}.",
        "My technical portfolio demonstrates a wide range of skills, including {skill}.",
        "I have a knack for {skill} and a passion for technology.",
        "My skills are not limited to {skill}; I am also proficient in {other_skill}.",
        "I have an intuitive understanding of {skill} principles.",
        "My professional journey has been a continuous process of skill acquisition in {field}.",
        "I am confident in my {skill} abilities and my capacity to deliver results.",
        "My skills in {skill} have been a major contributor to my professional success.",
        "I have a reputation for being a go-to person for {skill}-related challenges.",
        "I possess a robust skill set that includes {skill1}, {skill2}, and {tech}.",
        "My primary technical skills are in {skill} and its associated ecosystem."
    ],
    "Certifications": [
        "Achieved the {cert} certification.",
        "Completed the {cert} program online.",
        "Holds the {cert} credential.",
        "Certified in {cert}.",
        "Earned the {cert} designation.",
        "Successfully obtained the {cert} certification.",
        "Proud holder of the {cert} certification.",
        "My professional credentials include the {cert}.",
        "Validated my skills with the {cert} certification.",
        "I am a {cert} certified professional.",
        "Completed all requirements for the {cert} certification.",
        "Recipient of the {cert} certification.",
        "My qualifications are supported by the {cert} certification.",
        "Demonstrated proficiency by earning the {cert} certification.",
        "Holds a professional certification in {cert}.",
        "The {cert} is one of my key professional certifications.",
        "I have been awarded the {cert} certification.",
        "My expertise in {skill} is validated by the {cert} certification.",
        "I successfully passed the examination for the {cert} certification.",
        "I am certified by {issuer} with the {cert}.",
        "My list of achievements includes the {cert} certification.",
        "Gained the {cert} certification to enhance my skills in {tech}.",
        "I am officially recognized with the {cert} certification.",
        "My commitment to professional development is shown by my {cert} certification.",
        "I have acquired the {cert} credential.",
        "The {cert} certification has broadened my knowledge of {field}.",
        "My resume is strengthened by the {cert} certification.",
        "I am a proud recipient of the {cert} award.",
        "My continuous learning journey includes achieving the {cert}.",
        "I have met the rigorous standards of the {cert} certification.",
        "My professional profile features the {cert} certification.",
        "The {cert} certification attests to my skills in {area}.",
        "I have invested in my career by obtaining the {cert} certification.",
        "I am a certified {role} with the {cert} credential.",
        "My knowledge of {tech} is certified by the {cert}.",
        "I have completed the necessary training and exams for the {cert}.",
        "The {cert} is a testament to my dedication to excellence.",
        "My credentials are up-to-date with the recent {cert} certification.",
        "I am among the professionals who hold the {cert} certification.",
        "My skill in {skill} is officially certified by the {cert}.",
        "I have successfully completed the {cert} and am now certified.",
        "The {cert} certification has been a valuable addition to my skill set.",
        "I am qualified with the {cert} certification.",
        "My expertise is backed by the prestigious {cert} certification.",
        "I have demonstrated my abilities by achieving the {cert} certification.",
        "I am pleased to have earned the {cert} certification.",
        "My professional standing is enhanced by the {cert} certification.",
        "I have been certified with the {cert} since {year}.",
        "The {cert} certification is a key part of my professional identity.",
        "I have gone through the process and am now {cert} certified.",
        "My accomplishments include being awarded the {cert} certification.",
        "I am certified to an expert level with the {cert}.",
        "The {cert} certification has equipped me with advanced skills in {tech}.",
        "My portfolio of certifications includes the {cert}.",
        "I have earned the industry-recognized {cert} certification.",
        "The {cert} certification validates my extensive experience in {field}.",
        "I am a certified specialist, holding the {cert}.",
        "My professional qualifications are highlighted by the {cert} certification.",
        "I have attained the {cert} certification, a mark of professional distinction.",
        "The {cert} certification is a confirmation of my technical abilities.",
        "I am now a holder of the {cert}, a significant career milestone.",
        "My proficiency in {skill} is confirmed by my {cert} certification.",
        "I have successfully achieved the benchmark for the {cert} certification.",
        "The {cert} certification is a core component of my professional development.",
        "I am a certified practitioner with the {cert}.",
        "My dedication to my field is demonstrated by my {cert} certification.",
        "I have been granted the {cert} certification by {issuer}.",
        "The {cert} certification has been instrumental in my career growth.",
        "I have added the {cert} to my list of professional qualifications.",
        "My capabilities are certified by the {cert} credential.",
        "I am a professional with a {cert} certification.",
        "The {cert} certification represents my commitment to high standards.",
        "I have the {cert} certification, which is a globally recognized credential.",
        "My technical knowledge is validated by the {cert} certification.",
        "I am proud to be certified with the {cert}.",
        "The {cert} certification has been a goal of mine, which I have now achieved.",
        "I am a verified holder of the {cert} certification.",
        "My experience is complemented by the {cert} certification.",
        "I have passed the rigorous testing for the {cert} certification.",
        "The {cert} certification showcases my expertise in {domain}.",
        "I am certified in the latest technologies, including the {cert}.",
        "My professional certifications, such as the {cert}, attest to my skills.",
        "I have achieved a high level of proficiency, as shown by my {cert} certification.",
        "The {cert} certification is a valuable asset in my professional toolkit.",
        "I am a certified expert, as demonstrated by my {cert} credential.",
        "My resume includes the notable {cert} certification.",
        "I have fulfilled all the criteria to be awarded the {cert} certification.",
        "The {cert} certification from {issuer} is a key highlight of my profile.",
        "I am a professional who has earned the {cert} certification.",
        "My skills have been formally recognized with the {cert} certification.",
        "I have obtained the {cert} certification to stay current in my field.",
        "The {cert} certification is evidence of my advanced knowledge.",
        "I am certified and proficient, as indicated by the {cert}.",
        "My qualifications are formally endorsed by the {cert} certification.",
        "I have successfully earned my {cert} certification.",
        "The {cert} certification is a proud achievement in my professional life.",
        "I am a certified individual with a {cert} to my name.",
        "My expertise is certified and validated by the {cert}.",
        "I have completed the journey to become {cert} certified.",
        "The {cert} certification is a reflection of my skills and dedication."
    ]
}

def synonym_swap(sentence):
    replacements = {
        "worked": ["served", "was employed", "held a position"],
        "graduated": ["completed", "earned", "achieved"],
        "developed": ["built", "implemented", "created"],
        "proficient": ["skilled", "experienced", "adept"],
        "certified": ["credentialed", "licensed", "recognized"]
    }
    for k, v in replacements.items():
        if k in sentence:
            sentence = sentence.replace(k, random.choice(v))
    return sentence

def add_difficulty(sentence, level):
    if level == "easy":
        return sentence
    elif level == "medium":

        return sentence + " This strengthened my understanding of technical problem-solving."
    else:  

        extras = [
            "After completing this, I transitioned into applied research.",
            "It integrated theoretical and practical aspects of AI.",
            "This experience enhanced both my coding and leadership capabilities."
        ]
        return sentence + " " + random.choice(extras)

def generate_augmented_dataset(n_per_label=150, seed=42):
    random.seed(seed)
    data = []

    for label, tmpl_list in templates.items():
        for _ in range(n_per_label):
            t = random.choice(tmpl_list)

            class SafeDict(dict):
                def __missing__(self, key):
                    return ""

            mapping = {
                "degree": random.choice(degrees),
                "major": random.choice(majors),
                "university": random.choice(universities),
                "role": random.choice(roles),
                "company": random.choice(companies),
                "tech": random.choice(techs),
                "yrs": random.choice(years),
                "project": random.choice(projects),
                "purpose": random.choice(purposes),
                "tech1": random.choice(techs),
                "tech2": random.choice(techs),
                "tech3": random.choice(techs),
                "skill": random.choice(skills),
                "cert": random.choice(certs),
                "num": str(random.randint(1, 10)),
                "percentage": str(random.randint(5, 90)),
                "platform": random.choice(["web", "mobile", "cloud"]),
                "data_source": random.choice(["public datasets", "internal DBs", "APIs"]),
                "client": random.choice(companies),
                "sub_field": random.choice(majors),
                "course1": "", "course2": "", "gpa": "", "extracurricular_activity": "",
            }

            text = t.format_map(SafeDict(mapping))

            text = synonym_swap(text)
            level = random.choices(["easy", "medium", "hard"], weights=[0.4, 0.4, 0.2])[0]
            text = add_difficulty(text, level)

            if random.random() < 0.15:
                text = re.sub(r'\.', '', text)  
            if random.random() < 0.15:
                text = text.replace(" and ", " & ")

            data.append({"text": text.strip(), "label": label})
    return data

def paraphrase_with_ollama(prompt, model="llama3"):
    response = chat(model=model, messages=[
        {"role": "system", "content": "You are an NLP data augmentation assistant."},
        {"role": "user", "content": prompt}
    ])
    return response['message']['content']

def expand_dataset_with_ollama(seed_data, model="llama3", n_aug=3, delay=0.5):
    augmented = []
    for i, row in enumerate(seed_data):
        base_text = row['text']
        label = row['label']
        prompt = f"""Paraphrase the following {label.lower()} statement into {n_aug} unique, natural-sounding sentences of varied difficulty (easy, medium, hard).
Keep them realistic for a technical CV.
Sentence: "{base_text}"

Return JSON list: ["...", "...", "..."]"""

        try:
            output = paraphrase_with_ollama(prompt, model=model)
            try:
                variants = json.loads(output)
            except Exception:

                variants = [v.strip('- ') for v in output.split('\n') if len(v) > 5][:n_aug]
        except Exception as e:

            variants = []
            for _k in range(n_aug):
                v = base_text

                v = synonym_swap(v)
                v = add_difficulty(v, random.choice(["easy", "medium", "hard"]))
                if random.random() < 0.3:
                    v = v.replace(" and ", " & ")

                if random.random() < 0.15:
                    v = re.sub(r'\.$', '', v)
                variants.append(v)

            variants = variants[:n_aug]
            if len(variants) < n_aug:
                variants += [base_text] * (n_aug - len(variants))

        for v in variants:
            augmented.append({"text": v.strip(), "label": label})
        time.sleep(delay)  
        print(f"{i+1}/{len(seed_data)} processed")

    return augmented

purposes = ["predictive analytics", "automation", "customer retention", "sentiment analysis"]
years = ["1", "2", "3", "4", "5"]
dataset = generate_augmented_dataset(n_per_label=250)
dataset_aug = expand_dataset_with_ollama(dataset, model="llama3", n_aug=4)
print(f"Generated total: {len(dataset_aug)} samples")

import pandas as pd

df = pd.DataFrame(dataset_aug).drop_duplicates(subset=["text"])
df.to_csv("technical_cv_augmented_ollama.csv", index=False)
print(df.sample(5))
